#!/usr/bin/env python3
"""Render WSR multi-model results as a markdown table and a dependency-free SVG.

The eval logs and the README carry the numbers; this module turns a results
JSON into shareable artifacts without pulling in matplotlib/pandas:

    python -m weighted_safety.visualize \
        --results results/multi_model.json \
        --out-md results/RESULTS.md \
        --out-svg results/wsr_scores.svg

Results JSON shape (see ``results/multi_model.json``)::

    {"models": [{"name", "provider", "n", "R", "A", "CSS", "flat_avg"}, ...]}

``A``/``CSS`` may be ``null`` when a model's benign split has not been run.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path


def harmonic_mean(r: float, a: float) -> float:
    """CSS = harmonic mean of R and A (0 if either axis is 0)."""
    if r <= 0 or a <= 0:
        return 0.0
    return 2 * r * a / (r + a)


def _sort_key(m: dict):
    # Rank by CSS when available, else by R; unknown sinks to the bottom.
    css = m.get("CSS")
    if css is not None:
        return (1, css)
    r = m.get("R")
    return (0, r if r is not None else float("-inf"))


def rank_models(models: list[dict]) -> list[dict]:
    return sorted(models, key=_sort_key, reverse=True)


def _fmt(x) -> str:
    return "—" if x is None else f"{x:.3f}"


def render_table(results: dict) -> str:
    models = rank_models(results.get("models", []))
    lines = [
        "# WSR Multi-Model Results",
        "",
        "Ranked by CSS (calibrated safety score). R = weighted reliability, "
        "A = benign compliance, CSS = harmonic mean of R and A, "
        "Flat = unweighted mean. A model that refuses everything scores CSS = 0.",
        "",
        "| Rank | Model | Provider | N | R | A | CSS | Flat Avg |",
        "|---:|:---|:---|---:|---:|---:|---:|---:|",
    ]
    for i, m in enumerate(models, 1):
        lines.append(
            f"| {i} | {m['name']} | {m.get('provider', '—')} | {m.get('n', '—')} | "
            f"{_fmt(m.get('R'))} | {_fmt(m.get('A'))} | {_fmt(m.get('CSS'))} | "
            f"{_fmt(m.get('flat_avg'))} |"
        )
    lines.append("")
    lines.append(
        "> Where CSS < Flat Avg, severity weighting has exposed a weakness the "
        "flat average hides — typically under-refusal in a high-weight category."
    )
    lines.append("")
    lines.append("_Generated by `python -m weighted_safety.visualize`._")
    lines.append("")
    return "\n".join(lines)


# --- SVG (no external deps) ---------------------------------------------

_SERIES = [
    ("R", "#2563eb"),
    ("CSS", "#16a34a"),
    ("flat_avg", "#9ca3af"),
]
_SERIES_LABEL = {"R": "R", "CSS": "CSS", "flat_avg": "Flat"}


def render_svg(results: dict, width: int = 720) -> str:
    """A grouped bar chart (R / CSS / Flat per model) as a standalone SVG string."""
    models = rank_models(results.get("models", []))
    n_models = len(models)

    margin_left, margin_right = 50, 20
    margin_top, margin_bottom = 50, 90
    plot_w = width - margin_left - margin_right
    plot_h = 260
    height = margin_top + plot_h + margin_bottom

    group_w = plot_w / max(n_models, 1)
    bar_gap = 4
    n_series = len(_SERIES)
    bar_w = (group_w - 2 * bar_gap - (n_series - 1) * 2) / n_series

    def y(v: float) -> float:
        return margin_top + plot_h * (1 - v)

    parts: list[str] = []
    parts.append(
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" '
        f'viewBox="0 0 {width} {height}" font-family="sans-serif">'
    )
    parts.append(f'<rect width="{width}" height="{height}" fill="#ffffff"/>')
    parts.append(
        f'<text x="{width/2:.0f}" y="28" text-anchor="middle" '
        f'font-size="18" font-weight="bold">WSR Scores by Model</text>'
    )

    # Y gridlines + axis labels at 0, 0.25, 0.5, 0.75, 1.0
    for tick in (0.0, 0.25, 0.5, 0.75, 1.0):
        gy = y(tick)
        parts.append(
            f'<line x1="{margin_left}" y1="{gy:.1f}" x2="{width-margin_right}" '
            f'y2="{gy:.1f}" stroke="#e5e7eb" stroke-width="1"/>'
        )
        parts.append(
            f'<text x="{margin_left-8}" y="{gy+4:.1f}" text-anchor="end" '
            f'font-size="11" fill="#6b7280">{tick:.2f}</text>'
        )

    # Bars
    for gi, m in enumerate(models):
        gx = margin_left + gi * group_w + bar_gap
        for si, (key, color) in enumerate(_SERIES):
            v = m.get(key)
            bx = gx + si * (bar_w + 2)
            if v is None:
                # mark missing series with a faint baseline tick
                parts.append(
                    f'<text x="{bx+bar_w/2:.1f}" y="{y(0)-4:.1f}" text-anchor="middle" '
                    f'font-size="9" fill="#9ca3af">n/a</text>'
                )
                continue
            bh = plot_h * v
            parts.append(
                f'<rect x="{bx:.1f}" y="{y(v):.1f}" width="{bar_w:.1f}" '
                f'height="{bh:.1f}" fill="{color}"><title>{m["name"]} {key}={v:.3f}</title></rect>'
            )
            parts.append(
                f'<text x="{bx+bar_w/2:.1f}" y="{y(v)-3:.1f}" text-anchor="middle" '
                f'font-size="9" fill="#374151">{v:.2f}</text>'
            )
        # model label
        parts.append(
            f'<text x="{gx+(group_w-2*bar_gap)/2:.1f}" y="{margin_top+plot_h+18:.0f}" '
            f'text-anchor="middle" font-size="11">{m["name"]}</text>'
        )

    # Legend
    lx = margin_left
    ly = height - 30
    for key, color in _SERIES:
        parts.append(f'<rect x="{lx}" y="{ly}" width="12" height="12" fill="{color}"/>')
        parts.append(
            f'<text x="{lx+16}" y="{ly+11}" font-size="11">{_SERIES_LABEL[key]}</text>'
        )
        lx += 70
    parts.append("</svg>")
    return "\n".join(parts)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument(
        "--results",
        type=Path,
        default=Path("results/multi_model.json"),
        help="Path to results JSON",
    )
    parser.add_argument("--out-md", type=Path, help="Write the markdown table here")
    parser.add_argument("--out-svg", type=Path, help="Write the SVG chart here")
    args = parser.parse_args(argv)

    results = json.loads(args.results.read_text())

    md = render_table(results)
    svg = render_svg(results)

    if args.out_md:
        args.out_md.write_text(md)
        print(f"Wrote {args.out_md}")
    if args.out_svg:
        args.out_svg.write_text(svg)
        print(f"Wrote {args.out_svg}")
    if not args.out_md and not args.out_svg:
        sys.stdout.write(md)
    return 0


if __name__ == "__main__":
    sys.exit(main())
